package tree_sitter.c.node

import tree_sitter.Node

public class CommentNode(
    override val `$node`: Node,
) : CNodeBase,
    AbstractArrayDeclaratorNodeChildren,
    AbstractParenthesizedDeclaratorNodeChildren,
    AbstractPointerDeclaratorNodeChildren,
    AlignasQualifierNodeChildren,
    ArgumentListNodeChildren,
    ArrayDeclaratorNodeChildren,
    AttributeNodeChildren,
    AttributeDeclarationNodeChildren,
    AttributeSpecifierNodeChildren,
    AttributedDeclaratorNodeChildren,
    AttributedStatementNodeChildren,
    BitfieldClauseNodeChildren,
    CaseStatementNodeChildren,
    CharLiteralNodeChildren,
    CompoundStatementNodeChildren,
    ConcatenatedStringNodeChildren,
    DeclarationNodeChildren,
    DeclarationListNodeChildren,
    ElseClauseNodeChildren,
    EnumSpecifierNodeChildren,
    EnumeratorListNodeChildren,
    ExpressionStatementNodeChildren,
    ExtensionExpressionNodeChildren,
    FieldDeclarationNodeChildren,
    FieldDeclarationListNodeChildren,
    FieldDesignatorNodeChildren,
    FunctionDeclaratorNodeChildren,
    FunctionDefinitionNodeChildren,
    GenericExpressionNodeChildren,
    GnuAsmExpressionNodeChildren,
    InitializerListNodeChildren,
    LabeledStatementNodeChildren,
    MsBasedModifierNodeChildren,
    MsDeclspecModifierNodeChildren,
    MsPointerModifierNodeChildren,
    ParameterDeclarationNodeChildren,
    ParameterListNodeChildren,
    ParenthesizedDeclaratorNodeChildren,
    ParenthesizedExpressionNodeChildren,
    PointerDeclaratorNodeChildren,
    PreprocDefinedNodeChildren,
    PreprocElifNodeChildren,
    PreprocElifdefNodeChildren,
    PreprocElseNodeChildren,
    PreprocIfNodeChildren,
    PreprocIfdefNodeChildren,
    PreprocParamsNodeChildren,
    ReturnStatementNodeChildren,
    SehTryStatementNodeChildren,
    SizedTypeSpecifierNodeChildren,
    StringLiteralNodeChildren,
    StructSpecifierNodeChildren,
    SubscriptDesignatorNodeChildren,
    TranslationUnitNodeChildren,
    TypeDefinitionNodeChildren,
    TypeDescriptorNodeChildren,
    TypeQualifierNodeChildren,
    UnionSpecifierNodeChildren
