package buildsrc.convention

import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.MapProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFiles
import org.gradle.api.tasks.Internal
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction
import java.io.File
import java.util.concurrent.Callable
import java.util.concurrent.Executors

/**
 * Builds one shared library for one [NativeTarget] with zig (C, C++, linking) and
 * ISPC. Sources are compiled to objects in parallel, then linked.
 */
abstract class CompileCrossNativeTask : DefaultTask() {
    @get:Input
    abstract val target: Property<NativeTarget>

    @get:Input
    abstract val libraryName: Property<String>

    @get:InputFiles
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val cSources: ConfigurableFileCollection

    @get:InputFiles
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val cppSources: ConfigurableFileCollection

    @get:InputFiles
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val ispcSources: ConfigurableFileCollection

    /** Directories are fingerprinted with their contents, so header edits rerun the task. */
    @get:InputFiles
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val includeDirs: ConfigurableFileCollection

    @get:Input
    abstract val defines: MapProperty<String, String>

    @get:Input
    abstract val cFlags: ListProperty<String>

    @get:Input
    abstract val cppFlags: ListProperty<String>

    @get:Input
    abstract val ispcFlags: ListProperty<String>

    @get:Input
    abstract val linkFlags: ListProperty<String>

    @get:Input
    abstract val cStandard: Property<String>

    @get:Input
    abstract val cppStandard: Property<String>

    @get:Input
    abstract val optimization: Property<String>

    @get:Input
    abstract val ispcTargets: ListProperty<String>

    @get:Input
    abstract val strip: Property<Boolean>

    @get:Input
    abstract val toolchainId: Property<String>

    @get:Internal
    abstract val toolchains: Property<NativeToolchainService>

    /**
     * Working directory for zig. Inputs below it are passed as relative paths: zig 0.17 on
     * Windows intermittently panics ("missing prefix directory none") for absolute input
     * paths outside its cache and lib roots, because it compares the cwd handle read from
     * the PEB at two different times. Relative inputs resolve against the build root,
     * whose handle is captured once.
     */
    @get:Internal
    abstract val zigWorkingDir: DirectoryProperty

    @get:OutputFile
    abstract val outputLibrary: RegularFileProperty

    /** Headers generated by ISPC, kept as an output for inspection and probes. */
    @get:OutputDirectory
    abstract val generatedHeaders: DirectoryProperty

    @TaskAction
    fun compile() {
        val target = target.get()
        val service = toolchains.get()
        val work = temporaryDir.also {
            it.deleteRecursively()
            it.mkdirs()
        }
        val headers = generatedHeaders.get().asFile.also {
            it.deleteRecursively()
            it.mkdirs()
        }
        val objects = mutableListOf<File>()

        val ispcFiles = ispcSources.files.sortedBy { it.absolutePath }
        if (ispcFiles.isNotEmpty()) {
            val ispc = service.ispc()
            ispcFiles.forEachIndexed { index, source ->
                val objectDir = File(work, "ispc/$index").also { it.mkdirs() }
                val stem = source.nameWithoutExtension
                val command = buildList {
                    add(ispc.absolutePath)
                    add(source.absolutePath)
                    add(optimization.get())
                    add("--target-os=${target.ispcOs}")
                    add("--arch=${target.ispcArch}")
                    add("--target=" + ispcTargets.get().joinToString(","))
                    if (!target.isWindows) add("--pic")
                    addAll(ispcFlags.get())
                    add("-o")
                    add(File(objectDir, "$stem.o").absolutePath)
                    add("-h")
                    add(File(headers, "${stem}_ispc.h").absolutePath)
                }
                run(command, work, work, "ispc$index")
                // Multi-target builds emit one object per ISA plus a dispatcher object.
                objectDir.listFiles { file -> file.extension == "o" }!!.sortedBy { it.name }.forEach(objects::add)
            }
            // ISPC objects for Windows reference the MSVC CRT marker symbol _fltused,
            // which the MinGW runtime used by zig does not define.
            if (target.isWindows) {
                val stub = File(work, "caelum_fltused.c")
                stub.writeText("int _fltused = 0;\n")
                objects += compileC(stub, target, service, work, emptyList(), "fltused")
            }
        }

        val includes = buildList {
            add(headers)
            addAll(includeDirs.files)
        }
        val cJobs = cSources.files.sortedBy { it.absolutePath }.mapIndexed { index, source ->
            Callable { compileC(source, target, service, work, includes, "c$index") }
        }
        val cppJobs = cppSources.files.sortedBy { it.absolutePath }.mapIndexed { index, source ->
            Callable { compileCpp(source, target, service, work, includes, "cpp$index") }
        }
        val pool = Executors.newFixedThreadPool(Runtime.getRuntime().availableProcessors().coerceAtLeast(1))
        try {
            pool.invokeAll(cJobs + cppJobs).forEach { future ->
                try {
                    objects += future.get()
                } catch (e: java.util.concurrent.ExecutionException) {
                    throw e.cause ?: e
                }
            }
        } finally {
            pool.shutdownNow()
        }
        if (objects.isEmpty()) throw GradleException("No native sources configured for ${libraryName.get()}")

        val linked = File(work, target.libraryFileName(libraryName.get()))
        val link = buildList {
            add(service.zig().absolutePath)
            add(if (cppSources.isEmpty) "cc" else "c++")
            add("-target")
            add(target.zigTriple)
            add("-shared")
            if (strip.get()) add("-s")
            objects.forEach { add(zigPath(it)) }
            addAll(linkFlags.get())
            add("-o")
            add(linked.absolutePath)
        }
        run(link, zigWorkingDir.get().asFile, work, "link")
        val output = outputLibrary.get().asFile
        output.parentFile.mkdirs()
        linked.copyTo(output, overwrite = true)
    }

    private fun compileC(
        source: File, target: NativeTarget, service: NativeToolchainService, work: File, includes: List<File>, id: String,
    ): File = compileObject("cc", "-std=${cStandard.get()}", cFlags.get(), source, target, service, work, includes, id)

    private fun compileCpp(
        source: File, target: NativeTarget, service: NativeToolchainService, work: File, includes: List<File>, id: String,
    ): File = compileObject("c++", "-std=${cppStandard.get()}", cppFlags.get(), source, target, service, work, includes, id)

    private fun compileObject(
        driver: String,
        standard: String,
        flags: List<String>,
        source: File,
        target: NativeTarget,
        service: NativeToolchainService,
        work: File,
        includes: List<File>,
        id: String,
    ): File {
        val objectFile = File(work, "obj/$id-${source.nameWithoutExtension}.o")
        objectFile.parentFile.mkdirs()
        val command = buildList {
            add(service.zig().absolutePath)
            add(driver)
            add("-target")
            add(target.zigTriple)
            add(standard)
            add(optimization.get())
            if (!target.isWindows) add("-fPIC")
            defines.get().toSortedMap().forEach { (name, value) ->
                add(if (value.isEmpty()) "-D$name" else "-D$name=$value")
            }
            includes.forEach { add("-I${zigPath(it)}") }
            addAll(flags)
            add("-c")
            add(zigPath(source))
            add("-o")
            add(objectFile.absolutePath)
        }
        run(command, zigWorkingDir.get().asFile, work, id)
        return objectFile
    }

    /** Relative to [zigWorkingDir] when the file is below it, absolute otherwise. */
    private fun zigPath(file: File): String {
        val base = zigWorkingDir.get().asFile.toPath().toAbsolutePath().normalize()
        val path = file.toPath().toAbsolutePath().normalize()
        return if (path.startsWith(base) && path != base) base.relativize(path).toString() else path.toString()
    }

    private fun run(command: List<String>, directory: File, work: File, id: String) {
        val builder = ProcessBuilder(command).directory(directory).redirectErrorStream(true)
        // Keep zig's local cache inside the task, one directory per invocation so concurrent
        // compiles never share cache state. The global cache (libc, compiler-rt) stays shared.
        builder.environment()["ZIG_LOCAL_CACHE_DIR"] = File(work, "zig-cache/$id").absolutePath
        val process = builder.start()
        val output = process.inputStream.bufferedReader().readText()
        val exit = process.waitFor()
        if (exit != 0) {
            throw GradleException("Native command failed with exit $exit:\n${command.joinToString(" ")}\n$output")
        }
        if (output.isNotBlank()) logger.info(output)
    }
}
