package buildsrc.convention

import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.MapProperty
import org.gradle.api.provider.Property

/**
 * Declarative inputs for [CompileNativeLibraryTask].
 *
 * `apiDefines` are passed to the compiler so declarations seen by the generated
 * bindings and this implementation agree. `implementationDefines` are emitted
 * into the generated translation unit before its header includes.
 */
abstract class NativeLibraryExtension {
    abstract val libraryName: Property<String>

    /**
     * Explicit C++ translation units compiled into the library, for example a
     * generated `*_shim.cpp` and a header-only library implementation TU.
     */
    abstract val sources: ConfigurableFileCollection

    /**
     * Transitive SDK headers which affect compilation but are not included as
     * top-level headers in the generated implementation translation unit.
     */
    abstract val dependencyHeaders: ConfigurableFileCollection

    /** Headers included by the generated implementation translation unit. */
    abstract val headers: ConfigurableFileCollection
    abstract val includeDirs: ConfigurableFileCollection
    abstract val apiDefines: MapProperty<String, String>
    abstract val implementationDefines: MapProperty<String, String>

    /**
     * Whether the task compiles the generated header-inclusion translation
     * unit. Disable this when an explicit [sources] entry is the library's
     * implementation TU; keeping both would define implementation macros in
     * two translation units (for example `VMA_IMPLEMENTATION`).
     */
    abstract val generateImplementationSource: Property<Boolean>
    abstract val compilerExecutable: Property<String>
    abstract val cppStandard: Property<String>
    abstract val compileArgs: ListProperty<String>
    abstract val linkArgs: ListProperty<String>
    abstract val outputDirectory: DirectoryProperty

    /** The deterministic C++ implementation file generated by the compile task. */
    abstract val generatedImplementationSource: RegularFileProperty

    /** The shared-library artifact generated for the current host. */
    abstract val outputLibrary: RegularFileProperty

    init {
        apiDefines.convention(emptyMap())
        implementationDefines.convention(emptyMap())
        generateImplementationSource.convention(true)
        compileArgs.convention(emptyList())
        linkArgs.convention(emptyList())
    }
}
