package net.echonolix.caelum.codegen.cpp

import java.nio.file.Files
import java.nio.file.Path
import java.security.MessageDigest
import kotlin.io.path.createDirectories
import kotlin.io.path.writeText

public object CppCodegen {
    public fun generate(
        header: Path,
        outputDirectory: Path,
        config: CppCodegenConfig,
        clangExecutable: String = "clang++",
        compilerArguments: List<String> = emptyList(),
    ): CppGeneratedFiles {
        val module = ClangAst.parse(ClangAst.dump(header, clangExecutable, compilerArguments), header)
        return emit(module, header, outputDirectory, config)
    }

    public fun emit(module: CppModule, header: Path, outputDirectory: Path, config: CppCodegenConfig): CppGeneratedFiles {
        outputDirectory.createDirectories()
        val stem = config.moduleName.safeIdentifier()
        val headerOut = outputDirectory.resolve("${stem}_shim.h")
        val sourceOut = outputDirectory.resolve("${stem}_shim.cpp")
        val kotlinOut = outputDirectory.resolve("${config.kotlinObjectName}.kt")
        val diagnosticsOut = outputDirectory.resolve("${stem}_diagnostics.txt")
        headerOut.writeText(ShimEmitter.header(module, stem))
        sourceOut.writeText(ShimEmitter.source(module, stem, headerOut.fileName.toString(), header.toAbsolutePath().normalize().toString()))
        kotlinOut.writeText(KotlinEmitter.emit(module, config))
        diagnosticsOut.writeText(module.diagnostics.joinToString("\n") { "${it.declaration}: ${it.reason}" }.let { if (it.isEmpty()) it else "$it\n" })
        return CppGeneratedFiles(headerOut, sourceOut, kotlinOut, diagnosticsOut)
    }
}

private data class Export(val function: CppFunction, val symbol: String)

private fun CppModule.exports(): List<Export> = (functions + classes.flatMap { it.constructors + listOfNotNull(it.destructor) + it.methods })
    .map { Export(it, symbolFor(it)) }
    .sortedBy(Export::symbol)

internal fun symbolFor(function: CppFunction): String {
    val canonical = buildString {
        append(function.kind).append('|').append(function.qualifiedName).append('|')
        append(if (function.isConst) "const|" else "mutable|")
        append(function.parameters.joinToString(",") { it.type.canonical() }).append("->").append(function.returnType.canonical())
    }
    val digest = MessageDigest.getInstance("SHA-256").digest(canonical.toByteArray()).take(6).joinToString("") { "%02x".format(it) }
    return "caelum_${function.qualifiedName.safeIdentifier()}_$digest"
}

private fun CppType.canonical(): String = when (this) {
    CppType.Void -> "void"
    is CppType.Primitive -> value.cName
    is CppType.Pointer -> if (isConst) "const $pointee*" else "$pointee*"
    is CppType.Enum -> qualifiedName
}

internal fun String.safeIdentifier(): String = replace(Regex("[^A-Za-z0-9_]"), "_").replace(Regex("_+"), "_").trim('_').ifEmpty { "cpp" }

private object ShimEmitter {
    fun header(module: CppModule, stem: String): String = buildString {
        val guard = "CAELUM_${stem.uppercase()}_SHIM_H"
        appendLine("// Generated by Caelum codegen-cpp. Do not edit.")
        appendLine("#ifndef $guard")
        appendLine("#define $guard")
        appendLine("#include <stdbool.h>")
        appendLine("#include <stdint.h>")
        appendLine("#if defined(_WIN32)")
        appendLine("#define CAELUM_CPP_EXPORT __declspec(dllexport)")
        appendLine("#else")
        appendLine("#define CAELUM_CPP_EXPORT __attribute__((visibility(\"default\")))")
        appendLine("#endif")
        appendLine("#ifdef __cplusplus")
        appendLine("extern \"C\" {")
        appendLine("#endif")
        appendLine("CAELUM_CPP_EXPORT const char* caelum_${stem}_last_error(void);")
        module.enums.forEach { enum ->
            enum.values.forEach { (name, value) -> appendLine("#define CAELUM_${enum.qualifiedName.safeIdentifier().uppercase()}_${name.safeIdentifier().uppercase()} INT64_C($value)") }
        }
        module.exports().forEach { export -> appendLine(declaration(export) + ";") }
        appendLine("#ifdef __cplusplus")
        appendLine("}")
        appendLine("#endif")
        appendLine("#endif")
    }

    fun source(module: CppModule, stem: String, shimHeader: String, inputHeader: String): String = buildString {
        appendLine("// Generated by Caelum codegen-cpp. Do not edit.")
        appendLine("#include \"${escape(inputHeader)}\"")
        appendLine("#include \"$shimHeader\"")
        appendLine("#include <exception>")
        appendLine("#include <new>")
        appendLine("#include <string>")
        appendLine("namespace { thread_local std::string caelum_cpp_error; }")
        appendLine("extern \"C\" CAELUM_CPP_EXPORT const char* caelum_${stem}_last_error(void) { return caelum_cpp_error.c_str(); }")
        module.exports().forEach { export ->
            appendLine(declaration(export) + " {")
            appendLine("  try {")
            appendLine("    caelum_cpp_error.clear();")
            appendLine("    ${body(export.function)}")
            appendLine("    return 0;")
            appendLine("  } catch (const std::exception& e) { caelum_cpp_error = e.what(); return 1; }")
            appendLine("    catch (...) { caelum_cpp_error = \"unknown C++ exception\"; return 2; }")
            appendLine("}")
        }
    }

    private fun declaration(export: Export): String {
        val function = export.function
        val parameters = buildList {
            if (function.owner != null && function.kind in setOf(CppFunction.Kind.METHOD, CppFunction.Kind.DESTRUCTOR) && !function.isStatic) add("void* self")
            addAll(function.parameters.mapIndexed { index, parameter -> "${parameter.type.cType()} ${parameter.name.safeIdentifier().ifEmpty { "arg$index" }}" })
            if (function.kind == CppFunction.Kind.CONSTRUCTOR || function.returnType != CppType.Void) add("${function.returnType.outCType(function.kind)} out_result")
        }
        return "CAELUM_CPP_EXPORT int32_t ${export.symbol}(${parameters.ifEmpty { listOf("void") }.joinToString(", ")})"
    }

    private fun body(function: CppFunction): String {
        val args = function.parameters.joinToString(", ") { parameter ->
            when (val type = parameter.type) {
                is CppType.Enum -> "static_cast<${type.qualifiedName}>(${parameter.name.safeIdentifier()})"
                is CppType.Pointer -> "static_cast<${if (type.isConst) "const " else ""}${type.pointee}*>(${parameter.name.safeIdentifier()})"
                else -> parameter.name.safeIdentifier()
            }
        }
        val expression = when (function.kind) {
            CppFunction.Kind.CONSTRUCTOR -> "new ${function.namespace.plus(function.owner!!).joinToString("::")}($args)"
            CppFunction.Kind.DESTRUCTOR -> return "delete static_cast<${function.namespace.plus(function.owner!!).joinToString("::")}*>(self);"
            CppFunction.Kind.METHOD -> if (function.isStatic) {
                "${function.namespace.plus(function.owner!!).joinToString("::")}::${function.name}($args)"
            } else {
                val constPrefix = if (function.isConst) "const " else ""
                "static_cast<$constPrefix${function.namespace.plus(function.owner!!).joinToString("::")}*>(self)->${function.name}($args)"
            }
            CppFunction.Kind.FUNCTION -> "${function.namespace.plus(function.name).joinToString("::")}($args)"
        }
        if (function.kind == CppFunction.Kind.CONSTRUCTOR) return "*out_result = $expression;"
        return when (val type = function.returnType) {
            CppType.Void -> "$expression;"
            is CppType.Enum -> "*out_result = static_cast<int64_t>($expression);"
            else -> "*out_result = $expression;"
        }
    }

    private fun CppType.cType(): String = when (this) {
        CppType.Void -> "void"
        is CppType.Primitive -> when (value) {
            CppPrimitive.BOOL -> "bool"
            CppPrimitive.CHAR, CppPrimitive.INT8 -> "int8_t"
            CppPrimitive.UINT8 -> "uint8_t"
            CppPrimitive.INT16 -> "int16_t"
            CppPrimitive.UINT16 -> "uint16_t"
            CppPrimitive.INT32 -> "int32_t"
            CppPrimitive.UINT32 -> "uint32_t"
            CppPrimitive.INT64 -> "int64_t"
            CppPrimitive.UINT64 -> "uint64_t"
            CppPrimitive.FLOAT -> "float"
            CppPrimitive.DOUBLE -> "double"
        }
        is CppType.Pointer -> if (isConst) "const void*" else "void*"
        is CppType.Enum -> "int64_t"
    }

    private fun CppType.outCType(kind: CppFunction.Kind): String = if (kind == CppFunction.Kind.CONSTRUCTOR) "void**" else "${cType()}*"
    private fun escape(value: String): String = value.replace("\\", "\\\\").replace("\"", "\\\"")
}
