package net.echonolix.caelum.codegen.cpp

internal object KotlinEmitter {
    fun emit(module: CppModule, config: CppCodegenConfig): String = buildString {
        val names = KotlinNames(module)
        appendLine("// Generated by Caelum codegen-cpp. Do not edit.")
        appendLine("package ${config.kotlinPackage}")
        appendLine()
        appendLine("import java.lang.foreign.Arena")
        appendLine("import java.lang.foreign.FunctionDescriptor")
        appendLine("import java.lang.foreign.Linker")
        appendLine("import java.lang.foreign.MemorySegment")
        appendLine("import java.lang.foreign.SymbolLookup")
        appendLine("import java.lang.foreign.ValueLayout")
        appendLine("import java.lang.invoke.MethodHandle")
        appendLine("import java.nio.file.Path")
        appendLine("import java.util.concurrent.locks.ReentrantReadWriteLock")
        appendLine("import kotlin.concurrent.withLock")
        appendLine()
        appendLine("public object ${config.kotlinObjectName} : AutoCloseable {")
        appendLine("    private val arena: Arena = Arena.ofShared()")
        appendLine("    private val linker: Linker = Linker.nativeLinker()")
        appendLine("    private val lifecycle = ReentrantReadWriteLock()")
        appendLine("    private var closed: Boolean = false")
        appendLine("    private lateinit var lookup: SymbolLookup")
        appendLine("    public fun load(library: Path): Unit = lifecycle.writeLock().withLock { check(!closed) { \"native binding is closed\" }; check(!::lookup.isInitialized) { \"native library already loaded\" }; lookup = SymbolLookup.libraryLookup(library, arena) }")
        appendLine("    override fun close(): Unit = lifecycle.writeLock().withLock { if (!closed) { closed = true; arena.close() } }")
        appendLine("    private fun <T> withLibrary(block: () -> T): T = lifecycle.readLock().withLock { check(!closed) { \"native binding is closed\" }; check(::lookup.isInitialized) { \"native library is not loaded\" }; block() }")
        appendLine("    private fun handle(symbol: String, descriptor: FunctionDescriptor): MethodHandle = linker.downcallHandle(lookup.find(symbol).orElseThrow { UnsatisfiedLinkError(symbol) }, descriptor)")
        appendLine("    private fun lastError(): String { val address = handle(\"caelum_${config.moduleName.safeIdentifier()}_last_error\", FunctionDescriptor.of(ValueLayout.ADDRESS)).invokeWithArguments() as MemorySegment; return if (address.address() == 0L) \"\" else address.reinterpret(Long.MAX_VALUE).getString(0L) }")
        appendLine("    private fun checkStatus(status: Int) { if (status != 0) throw CppException(status, lastError()) }")
        appendLine("    public class CppException(public val status: Int, detail: String) : RuntimeException(if (detail.isEmpty()) \"C++ shim failed with status ${'$'}status\" else detail)")
        appendLine()
        module.enums.forEach { enum ->
            val enumName = names.type(enum.qualifiedName).kotlinIdentifier()
            appendLine("    public enum class $enumName(public val nativeValue: Long) {")
            enum.values.forEachIndexed { index, entry -> appendLine("        ${entry.first.kotlinIdentifier()}(${entry.second}L)${if (index == enum.values.lastIndex) ";" else ","}") }
            appendLine("        public companion object { public fun fromNative(value: Long): $enumName = entries.firstOrNull { it.nativeValue == value } ?: error(\"unknown $enumName value: ${'$'}value\") }")
            appendLine("    }")
        }
        module.functions.forEach { emitFunction(it, symbolFor(it), null, names) }
        module.classes.forEach { clazz ->
            val className = names.type(clazz.qualifiedName).kotlinIdentifier()
            appendLine("    public class $className internal constructor(public val segment: MemorySegment) : AutoCloseable {")
            appendLine("        private var closed: Boolean = false")
            appendLine("        private fun requireOpen() { check(!closed) { \"$className is closed\" } }")
            clazz.methods.filterNot(CppFunction::isStatic).forEach { emitFunction(it, symbolFor(it), className, names, "        ", synchronized = true) }
            clazz.destructor?.let { destructor ->
                val symbol = symbolFor(destructor)
                appendLine("        @Synchronized override fun close() { if (!closed) { withLibrary { checkStatus(handle(\"$symbol\", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS)).invokeWithArguments(segment) as Int) }; closed = true } }")
            } ?: appendLine("        override fun close(): Unit = error(\"$className has no public destructor\")")
            appendLine("    }")
            clazz.constructors.forEach { emitFunction(it, symbolFor(it), className, names) }
            clazz.methods.filter(CppFunction::isStatic).forEach { emitFunction(it, symbolFor(it), className, names) }
        }
        appendLine("}")
    }

    private fun StringBuilder.emitFunction(function: CppFunction, symbol: String, kotlinClass: String?, names: KotlinNames, indent: String = "    ", synchronized: Boolean = false) {
        val publicName = names.function(function).kotlinIdentifier()
        val kotlinParameters = function.parameters.joinToString(", ") { "${it.name.kotlinIdentifier()}: ${it.type.kotlinType(names)}" }
        val returnType = if (function.kind == CppFunction.Kind.CONSTRUCTOR) kotlinClass!! else function.returnType.kotlinType(names)
        appendLine("$indent${if (synchronized) "@Synchronized " else ""}public fun $publicName($kotlinParameters): $returnType = withLibrary {")
        if (function.owner != null && function.kind == CppFunction.Kind.METHOD && !function.isStatic) appendLine("${indent}    requireOpen()")
        appendLine("${indent}    Arena.ofConfined().use { callArena ->")
        val layouts = buildList {
            if (function.owner != null && function.kind == CppFunction.Kind.METHOD && !function.isStatic) add("ValueLayout.ADDRESS")
            addAll(function.parameters.map { it.type.layout() })
            if (function.kind == CppFunction.Kind.CONSTRUCTOR || function.returnType != CppType.Void) add("ValueLayout.ADDRESS")
        }
        appendLine("${indent}        val descriptor = FunctionDescriptor.of(ValueLayout.JAVA_INT${layouts.joinToString("") { ", $it" }})")
        if (function.kind == CppFunction.Kind.CONSTRUCTOR || function.returnType != CppType.Void) appendLine("${indent}        val out = callArena.allocate(${if (function.kind == CppFunction.Kind.CONSTRUCTOR) "ValueLayout.ADDRESS" else function.returnType.layout()})")
        val args = buildList {
            if (function.owner != null && function.kind == CppFunction.Kind.METHOD && !function.isStatic) add("segment")
            addAll(function.parameters.map { it.type.argument(it.name.kotlinIdentifier()) })
            if (function.kind == CppFunction.Kind.CONSTRUCTOR || function.returnType != CppType.Void) add("out")
        }
        appendLine("${indent}        checkStatus(handle(\"$symbol\", descriptor).invokeWithArguments(${args.joinToString(", ")}) as Int)")
        val result = when {
            function.kind == CppFunction.Kind.CONSTRUCTOR -> "$kotlinClass(out.get(ValueLayout.ADDRESS, 0L))"
            function.returnType == CppType.Void -> "Unit"
            else -> function.returnType.read("out", names)
        }
        appendLine("${indent}        $result")
        appendLine("${indent}    }")
        appendLine("${indent}}")
    }
}

/** Assigns names after Kotlin type projection, preserving source names unless they collide. */
private class KotlinNames(module: CppModule) {
    private val typeNames: Map<String, String> = run {
        val qualifiedNames = module.enums.map(CppEnum::qualifiedName) + module.classes.map(CppClass::qualifiedName)
        val readable = qualifiedNames.groupBy { it.substringAfterLast("::") }
            .flatMap { (short, qualified) -> qualified.map { it to if (qualified.size == 1) short else it.split("::").joinToString("") { part -> part.toPascalCase() } } }
        val duplicates = readable.groupBy({ it.second }, { it.first }).filterValues { it.size > 1 }.keys
        readable.associate { (qualified, candidate) ->
            qualified to if (candidate in duplicates) "${candidate}_${stableHash(qualified)}" else candidate
        }
    }

    private val functionNames: Map<CppFunction, String> = buildMap {
        val all = module.functions + module.classes.flatMap { it.constructors + it.methods }
        all.groupBy { function ->
            val container = if (function.kind == CppFunction.Kind.METHOD && !function.isStatic) function.owner else null
            val base = if (function.kind == CppFunction.Kind.CONSTRUCTOR) "create${type((function.namespace + function.owner!!).joinToString("::"))}" else function.name
            Triple(container, base, function.parameters.map { it.type.kotlinType(this@KotlinNames) })
        }.forEach { (_, collisions) ->
            val readableCandidates = collisions.associateWith { function ->
                val base = if (function.kind == CppFunction.Kind.CONSTRUCTOR) "create${type((function.namespace + function.owner!!).joinToString("::"))}" else function.name
                if (collisions.size == 1) base else base + "_" + disambiguator(function)
            }
            val duplicateCandidates = readableCandidates.entries.groupBy({ it.value }, { it.key })
                .filterValues { it.size > 1 }
                .keys
            readableCandidates.forEach { (function, candidate) ->
                val uniqueName = if (candidate in duplicateCandidates) "${candidate}_${symbolFor(function).substringAfterLast('_')}" else candidate
                put(function, uniqueName)
            }
        }
    }

    fun type(qualifiedName: String): String = typeNames.getValue(qualifiedName)
    fun function(function: CppFunction): String = functionNames.getValue(function)

    private fun disambiguator(function: CppFunction): String = buildList {
        if (function.kind == CppFunction.Kind.FUNCTION || function.isStatic) {
            addAll(function.namespace.map { it.safeIdentifier().lowercase() })
            if (function.isStatic) add(function.owner!!.safeIdentifier().lowercase())
        }
        addAll(function.parameters.map { it.type.abiTag() })
        if (function.isConst) add("const")
    }.ifEmpty { listOf(symbolFor(function).substringAfterLast('_')) }.joinToString("_")
}

private fun stableHash(value: String): String = java.security.MessageDigest.getInstance("SHA-256")
    .digest(value.toByteArray())
    .take(6)
    .joinToString("") { "%02x".format(it) }

private fun CppType.abiTag(): String = when (this) {
    CppType.Void -> "void"
    is CppType.Primitive -> value.cName.safeIdentifier().lowercase()
    is CppType.Pointer -> (if (isConst) "const_" else "") + pointee.safeIdentifier().lowercase() + "_ptr"
    is CppType.Enum -> qualifiedName.safeIdentifier().lowercase()
}

private fun CppType.kotlinType(names: KotlinNames): String = when (this) {
    CppType.Void -> "Unit"
    is CppType.Primitive -> value.kotlinName
    is CppType.Pointer -> "MemorySegment"
    is CppType.Enum -> names.type(qualifiedName).kotlinIdentifier()
}

private fun CppType.layout(): String = when (this) {
    CppType.Void -> error("void has no layout")
    is CppType.Primitive -> "ValueLayout.${value.layout}"
    is CppType.Pointer -> "ValueLayout.ADDRESS"
    is CppType.Enum -> "ValueLayout.JAVA_LONG"
}

private fun CppType.argument(name: String): String = when (this) {
    is CppType.Enum -> "$name.nativeValue"
    is CppType.Primitive -> if (value == CppPrimitive.BOOL) "if ($name) 1.toByte() else 0.toByte()" else name
    else -> name
}

private fun CppType.read(out: String, names: KotlinNames): String = when (this) {
    is CppType.Enum -> "${names.type(qualifiedName).kotlinIdentifier()}.fromNative($out.get(ValueLayout.JAVA_LONG, 0L))"
    is CppType.Primitive -> if (value == CppPrimitive.BOOL) "$out.get(ValueLayout.JAVA_BYTE, 0L).toInt() != 0" else "$out.get(${layout()}, 0L)"
    else -> "$out.get(${layout()}, 0L)"
}

private val kotlinKeywords = setOf(
    "as", "break", "class", "continue", "do", "else", "false", "for", "fun", "if", "in", "interface",
    "is", "null", "object", "package", "return", "super", "this", "throw", "true", "try", "typealias",
    "typeof", "val", "var", "when", "while", "by", "catch", "constructor", "delegate", "dynamic", "field",
    "file", "finally", "get", "import", "init", "param", "property", "receiver", "set", "setparam", "where",
    "actual", "abstract", "annotation", "companion", "const", "crossinline", "data", "enum", "expect", "external",
    "final", "infix", "inline", "inner", "internal", "lateinit", "noinline", "open", "operator", "out", "override",
    "private", "protected", "public", "reified", "sealed", "suspend", "tailrec", "vararg",
)

private fun String.kotlinIdentifier(): String {
    val identifier = safeIdentifier()
    return if (identifier in kotlinKeywords || identifier.firstOrNull()?.isDigit() == true) "`$identifier`" else identifier
}
